import BaseTypography from '@@components/Typography/BaseTypography';
import { TYPOGRAPHY_THEME } from '@@components/Typography/constants';

const Typography = {
  [TYPOGRAPHY_THEME.TITLE_1]: BaseTypography(TYPOGRAPHY_THEME.TITLE_1),
  [TYPOGRAPHY_THEME.TITLE_2]: BaseTypography(TYPOGRAPHY_THEME.TITLE_2),
  [TYPOGRAPHY_THEME.TITLE_3]: BaseTypography(TYPOGRAPHY_THEME.TITLE_3),
  [TYPOGRAPHY_THEME.TITLE_4]: BaseTypography(TYPOGRAPHY_THEME.TITLE_4),
  [TYPOGRAPHY_THEME.TITLE_5]: BaseTypography(TYPOGRAPHY_THEME.TITLE_5),

  [TYPOGRAPHY_THEME.SUBTITLE_1]: BaseTypography(TYPOGRAPHY_THEME.SUBTITLE_1),
  [TYPOGRAPHY_THEME.SUBTITLE_2]: BaseTypography(TYPOGRAPHY_THEME.SUBTITLE_2),
  [TYPOGRAPHY_THEME.SUBTITLE_3]: BaseTypography(TYPOGRAPHY_THEME.SUBTITLE_3),

  [TYPOGRAPHY_THEME.BODY_1]: BaseTypography(TYPOGRAPHY_THEME.BODY_1),
  [TYPOGRAPHY_THEME.BODY_2]: BaseTypography(TYPOGRAPHY_THEME.BODY_2),
  [TYPOGRAPHY_THEME.BODY_3]: BaseTypography(TYPOGRAPHY_THEME.BODY_3),

  [TYPOGRAPHY_THEME.CAPTION_1]: BaseTypography(TYPOGRAPHY_THEME.CAPTION_1),
  [TYPOGRAPHY_THEME.CAPTION_2]: BaseTypography(TYPOGRAPHY_THEME.CAPTION_2),

  [TYPOGRAPHY_THEME.BUTTON_1]: BaseTypography(TYPOGRAPHY_THEME.BUTTON_1),
  [TYPOGRAPHY_THEME.BUTTON_2]: BaseTypography(TYPOGRAPHY_THEME.BUTTON_2),
  [TYPOGRAPHY_THEME.BUTTON_3]: BaseTypography(TYPOGRAPHY_THEME.BUTTON_3),
};

export default Typography;
